### ISSUE TITLE
Can't clone onto windows 0/10

### ISSUE THREAD

**Issue by EntropicBlackhole** [programmerhumor-discord/the-repository#15]
The readme:ducks-only.md file can't be created on windows due to the :, I kindly request you to rename the file

**Comment by D-u-c-k-s-e-l** [comment]
I think it's fixed?!?!?!??!?!??!?!??!?!??!??!?!?!?

I am going inslanieeee...

**Comment by D-u-c-k-s-e-l** [comment]
is it?
fixed

**Comment by heladeradr** [comment]
while we fix this issue, i found a workaround
there's this piece of software called fedora workstation
https://fedoraproject.org/es/workstation/
you should install it

**Comment by EntropicBlackhole** [comment]
Yes!

**Comment by EntropicBlackhole** [comment]
Thank you!
